### ISSUE TITLE
Tooling internal exception still generates and empty reports

### ISSUE THREAD

**Issue by tasomaniac** [JetBrains/inspection-plugin#15]
When an internal exception happens, the Gradle task goes successful and the plugin generates empty reports.

I have `ignoreFailures = true` but that should be different. That would ignore failures in my codebase not errors during evaluation.

An internal problem should throw and break the build.

**Comment by tasomaniac** [comment]
Here is an example output. Re-run fixes the issue for me. It happens time to time though. When this happens build was sucessful

<details>
WARN: null
java.lang.NullPointerException
	at com.intellij.build.BuildContentManagerImpl.lambda$init$0(BuildContentManagerImpl.java:94)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runWhenProjectIsInitialized$5(StartupManagerImpl.java:396)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:377)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runWhenProjectIsInitialized(StartupManagerImpl.java:398)
	at com.intellij.build.BuildContentManagerImpl.init(BuildContentManagerImpl.java:91)
	at com.intellij.build.BuildContentManagerImpl.<init>(BuildContentManagerImpl.java:84)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:220)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at org.picocontainer.defaults.BasicComponentParameter.resolveInstance(BasicComponentParameter.java:77)
	at org.picocontainer.defaults.ComponentParameter.resolveInstance(ComponentParameter.java:114)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getConstructorArguments(CachingConstructorInjectionComponentAdapter.java:129)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:100)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:220)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:49)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:43)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3$3.onStart(ExternalSystemUtil.java:471)
	at com.intellij.openapi.externalSystem.service.remote.ExternalSystemProgressNotificationManagerImpl.onStart(ExternalSystemProgressNotificationManagerImpl.java:74)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:85)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:163)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:149)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:522)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$5.run(ExternalSystemUtil.java:581)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:704)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:388)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:554)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:400)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:296)
	at com.intellij.openapi.progress.Task.queue(Task.java:115)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil.refreshProject(ExternalSystemUtil.java:583)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil.refreshProject(ExternalSystemUtil.java:372)
	at com.android.tools.idea.gradle.project.sync.idea.IdeaGradleSync.sync(IdeaGradleSync.java:141)
	at com.android.tools.idea.gradle.project.sync.GradleSyncInvoker.sync(GradleSyncInvoker.java:200)
	at com.android.tools.idea.gradle.project.sync.GradleSyncInvoker.lambda$requestProjectSync$1(GradleSyncInvoker.java:106)
	at com.intellij.ui.AppUIUtil.invokeLaterIfProjectAlive(AppUIUtil.java:109)
	at com.android.tools.idea.gradle.project.sync.GradleSyncInvoker.requestProjectSync(GradleSyncInvoker.java:115)
	at com.android.tools.idea.gradle.project.AndroidGradleProjectStartupActivity.runActivity(AndroidGradleProjectStartupActivity.java:31)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runAndMeasure(StartupManagerImpl.java:176)
	at com.intellij.ide.startup.impl.StartupManagerImpl.logActivityDuration(StartupManagerImpl.java:162)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivitiesFromExtensions$1(StartupManagerImpl.java:150)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:367)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$queueSmartModeActivity$2(StartupManagerImpl.java:182)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:170)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runWhenProjectIsInitialized$5(StartupManagerImpl.java:396)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:377)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runWhenProjectIsInitialized(StartupManagerImpl.java:398)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:162)
	at com.intellij.ide.startup.impl.StartupManagerImpl.queueSmartModeActivity(StartupManagerImpl.java:182)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivitiesFromExtensions(StartupManagerImpl.java:155)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$openProject$8(ProjectManagerImpl.java:411)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectUnderProgress(ProjectManagerImpl.java:448)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:431)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:508)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:499)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:326)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:704)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:388)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:554)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:400)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:296)
	at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:190)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:499)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:191)
	at com.intellij.ide.impl.ProjectUtil.openOrImport(ProjectUtil.java:117)
	at org.jetbrains.idea.inspections.IdeaRunner$openProject$1.invoke(IdeaRunner.kt:44)
	at org.jetbrains.idea.inspections.IdeaRunner$openProject$1.invoke(IdeaRunner.kt:35)
	at org.jetbrains.idea.inspections.IdeaRunnerKt$sam$Runnable$d10e6147.run(IdeaRunner.kt)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:158)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
InspectionPlugin: Analyzing exception
Caused by: org.jetbrains.idea.inspections.RunnerException: Exception caught in inspection plugin: com.intellij.psi.PsiInvalidElementAccessException: Element: class org.jetbrains.kotlin.psi.KtFile because: different providers: SingleRootFileViewProvider{myVirtualFile=file:///Users/tasomaniac/dev/nos/gradle-static-analysis-plugin/sample-multi-module/app/src/main/java/com/novoda/staticanalysisplugin/sample/MyActivity.kt, content=VirtualFileContent{size=1040}}(10ed4dc8); SingleRootFileViewProvider{myVirtualFile=file:///Users/tasomaniac/dev/nos/gradle-static-analysis-plugin/sample-multi-module/app/src/main/java/com/novoda/staticanalysisplugin/sample/MyActivity.kt, content=VirtualFileContent{size=1040}}(761c3f2c)
invalidated at: see attachment
    org.jetbrains.idea.inspections.IdeaRunner.run(IdeaRunner.kt:155)
    org.jetbrains.intellij.tasks.AbstractInspectionsTask$run$inspectionsThread$1.invoke(AbstractInspectionsTask.kt:304)
    org.jetbrains.intellij.tasks.AbstractInspectionsTask$run$inspectionsThread$1.invoke(AbstractInspectionsTask.kt:26)
    kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: com.intellij.psi.PsiInvalidElementAccessException: Element: class org.jetbrains.kotlin.psi.KtFile because: different providers: SingleRootFileViewProvider{myVirtualFile=file:///Users/tasomaniac/dev/nos/gradle-static-analysis-plugin/sample-multi-module/app/src/main/java/com/novoda/staticanalysisplugin/sample/MyActivity.kt, content=VirtualFileContent{size=1040}}(10ed4dc8); SingleRootFileViewProvider{myVirtualFile=file:///Users/tasomaniac/dev/nos/gradle-static-analysis-plugin/sample-multi-module/app/src/main/java/com/novoda/staticanalysisplugin/sample/MyActivity.kt, content=VirtualFileContent{size=1040}}(761c3f2c)
invalidated at: see attachment
    com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:502)
    com.intellij.psi.impl.source.PsiFileImpl.getTextLength(PsiFileImpl.java:346)
    com.intellij.psi.impl.source.PsiFileImpl.getTextRange(PsiFileImpl.java:352)
    org.jetbrains.idea.inspections.InspectionsRunner.analyze(InspectionsRunner.kt:381)
    org.jetbrains.idea.inspections.InspectionsRunner.access$analyze(InspectionsRunner.kt:27)
    org.jetbrains.idea.inspections.InspectionsRunner$apply$1$task$1.run(InspectionsRunner.kt:192)
    com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
    com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:534)
    com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
    com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    org.jetbrains.idea.inspections.InspectionsRunner$apply$1.invoke(InspectionsRunner.kt:208)
    org.jetbrains.idea.inspections.InspectionsRunner$apply$1.invoke(InspectionsRunner.kt:27)
    org.jetbrains.idea.inspections.IdeaRunnerKt$sam$Runnable$d10e6147.run(IdeaRunner.kt)
    com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:912)
    org.jetbrains.idea.inspections.IdeaRunner.runReadAction(IdeaRunner.kt:99)
    org.jetbrains.idea.inspections.InspectionsRunner.apply(InspectionsRunner.kt:185)
    org.jetbrains.idea.inspections.InspectionsRunner.analyze(InspectionsRunner.kt:134)
    org.jetbrains.idea.inspections.InspectionsRunner.analyzeFileInfo(InspectionsRunner.kt:111)
    org.jetbrains.idea.inspections.InspectionsRunner.analyzeFileInfo(InspectionsRunner.kt:27)
    org.jetbrains.idea.inspections.FileInfoRunner.analyze(FileInfoRunner.kt:65)
    org.jetbrains.idea.inspections.IdeaRunner.run(IdeaRunner.kt:152)
    org.jetbrains.intellij.tasks.AbstractInspectionsTask$run$inspectionsThread$1.invoke(AbstractInspectionsTask.kt:304)
    org.jetbrains.intellij.tasks.AbstractInspectionsTask$run$inspectionsThread$1.invoke(AbstractInspectionsTask.kt:26)
    kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

</details>

**Comment by mglukhikh** [comment]
I'm not quite sure but think it should be fixed in 0.3.0 version.
